language: python
python:
  - "3.6"

install:
  - pip install flit
  - flit install -s --deps all

script:
  - pytest

deploy:
  provider: script
  script: flit release
  on:
    tags: true

branches:
  except:
    - dev
